version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "27017:27017"

  pcs-image:
    image: pcs-image:1.0
    container_name: pcs-container
    ports:
      - "8080:8080"
    links:
      - db